import { Profile } from './types'

export const PROFILES: Profile[] = [
    // ─── Rendimentos altos ───────────────────────────────────────────
    {
        id: 'ana',
        emoji: '👩',
        imageUrl: '/profiles/ana.jpg',
        name: 'Ana Ferreira',
        age: 29,
        role: 'Consultora de gestão · KPMG',
        bio: 'Gosto de viajar e de pessoas que saibam o que querem da vida.',
        monthlyIncome: 4800,
        lifestyle: 'premium',
        appearanceScore: 8,
        hasOwnHome: true,
        hasChildren: false,
        educationLevel: 5,
        phenomenon: 'normal',
    },
    {
        id: 'marta',
        emoji: '🧑',
        imageUrl: '/profiles/marta.jpg',
        name: 'Marta Oliveira',
        age: 34,
        role: 'Médica especialista · Hospital São João',
        bio: 'Trabalho muito. Tenho pouco tempo mas sei usá-lo bem.',
        monthlyIncome: 6200,
        lifestyle: 'luxo',
        appearanceScore: 7,
        hasOwnHome: true,
        hasChildren: false,
        educationLevel: 5,
        phenomenon: 'normal',
    },
    {
        id: 'ines',
        emoji: '👩‍🦱',
        imageUrl: '/profiles/ines.jpg',
        name: 'Inês Rodrigues',
        age: 36,
        role: 'Advogada sénior · sócia fundadora',
        bio: 'Directa e independente. Procuro alguém seguro de si.',
        monthlyIncome: 7500,
        lifestyle: 'luxo',
        appearanceScore: 8,
        hasOwnHome: true,
        hasChildren: false,
        educationLevel: 5,
        phenomenon: 'normal',
    },
    {
        id: 'sofia',
        emoji: '👩‍💻',
        imageUrl: '/profiles/sofia.jpg',
        name: 'Sofia Mendes',
        age: 28,
        role: 'Engenheira de software · startup',
        bio: 'Construo coisas. Prefiro conversas longas a jantares caros.',
        monthlyIncome: 5200,
        lifestyle: 'premium',
        appearanceScore: 7,
        hasOwnHome: false,
        hasChildren: false,
        educationLevel: 5,
        phenomenon: 'chatfishing',
    },
    {
        id: 'david',
        emoji: '👨‍💼',
        imageUrl: '/profiles/david.jpg',
        name: 'David Chen',
        age: 38,
        role: 'Gestor de fundos · Singapura/Lisboa',
        bio: 'Viajo muito. Acredito que o sucesso se partilha.',
        monthlyIncome: 28000,
        lifestyle: 'luxo',
        appearanceScore: 8,
        hasOwnHome: true,
        hasChildren: false,
        educationLevel: 5,
        phenomenon: 'pig_butchering',
    },
    {
        id: 'miguel',
        emoji: '👨‍🦳',
        imageUrl: '/profiles/miguel.jpg',
        name: 'Miguel Costa',
        age: 42,
        role: 'Professor do 1.º ciclo · escola pública',
        bio: 'Ensino crianças há 15 anos. Acredito que as pessoas valem mais do que ganham.',
        monthlyIncome: 1200,
        lifestyle: 'modesto',
        appearanceScore: 6,
        hasOwnHome: false,
        hasChildren: false,
        educationLevel: 5,
        phenomenon: 'normal',
    },
    {
        id: 'rui',
        emoji: '👨',
        imageUrl: '/profiles/rui.jpg',
        name: 'Rui Santos',
        age: 27,
        role: 'Monitor de ginásio · freelance',
        bio: 'Tenho pouco mas dou muito. Apaixonado por pessoas autênticas.',
        monthlyIncome: 950,
        lifestyle: 'básico',
        appearanceScore: 9,
        hasOwnHome: false,
        hasChildren: false,
        educationLevel: 2,
        phenomenon: 'normal',
    },
    {
        id: 'nuno',
        emoji: '👱',
        imageUrl: '/profiles/nuno.jpg',
        name: 'Nuno Carvalho',
        age: 31,
        role: 'Assistente de loja · Fnac',
        bio: 'Leio muito, ouço jazz, sou fiel. Não tenho carro mas tenho bicicleta.',
        monthlyIncome: 900,
        lifestyle: 'básico',
        appearanceScore: 7,
        hasOwnHome: false,
        hasChildren: false,
        educationLevel: 3,
        phenomenon: 'normal',
    },
    {
        id: 'catarina',
        emoji: '👩‍🍳',
        imageUrl: '/profiles/catarina.jpg',
        name: 'Catarina Lopes',
        age: 33,
        role: 'Cozinheira · restaurante familiar',
        bio: 'Faço o pão todos os dias às 5h. O meu avô ensinou-me a cozinhar.',
        monthlyIncome: 850,
        lifestyle: 'modesto',
        appearanceScore: 7,
        hasOwnHome: false,
        hasChildren: true,
        educationLevel: 2,
        phenomenon: 'normal',
    },
    {
        id: 'bruno',
        emoji: '🧑‍🔧',
        imageUrl: '/profiles/bruno.jpg',
        name: 'Bruno Almeida',
        age: 29,
        role: 'Técnico de manutenção · câmara municipal',
        bio: 'Conserto o que está partido. Gosto de coisas simples e bem feitas.',
        monthlyIncome: 1050,
        lifestyle: 'modesto',
        appearanceScore: 6,
        hasOwnHome: false,
        hasChildren: false,
        educationLevel: 3,
        phenomenon: 'normal',
    },
    {
        id: 'teresa',
        emoji: '👵',
        name: 'Teresa Marques',
        imageUrl: '/profiles/teresa.jpg',
        age: 39,
        role: 'Enfermeira · centro de saúde',
        bio: 'Cuido de pessoas todos os dias. Às vezes esqueço-me de cuidar de mim.',
        monthlyIncome: 1350,
        lifestyle: 'básico',
        appearanceScore: 6,
        hasOwnHome: true,
        hasChildren: true,
        educationLevel: 4,
        phenomenon: 'normal',
    },
    {
        id: 'joao',
        emoji: '🧑‍🌾',
        imageUrl: '/profiles/joao.jpg',
        name: 'João Pereira',
        age: 35,
        role: 'Agricultor · produção própria',
        bio: 'Trabalho a terra do meu pai. Não troco isto por nada.',
        monthlyIncome: 780,
        lifestyle: 'modesto',
        appearanceScore: 5,
        hasOwnHome: true,
        hasChildren: false,
        educationLevel: 1,
        phenomenon: 'normal',
    },
    {
        id: 'mariana',
        emoji: '👩‍🎨',
        imageUrl: '/profiles/mariana.jpg',
        name: 'Mariana Costa',
        age: 26,
        role: 'Ilustradora · freelancer',
        bio: 'Vivo do que desenho. Nem sempre há trabalho, mas nunca desisto.',
        monthlyIncome: 700,
        lifestyle: 'modesto',
        appearanceScore: 8,
        hasOwnHome: false,
        hasChildren: false,
        educationLevel: 4,
        phenomenon: 'normal',
    },
]